// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJtc33sAZgzpOjhn_TjX0hxBCd5_BFck',
    appId: '1:88909482704:web:a5800977240dfeb0bb2cd5',
    messagingSenderId: '88909482704',
    projectId: 'anystay-e2a14',
    authDomain: 'anystay-e2a14.firebaseapp.com',
    storageBucket: 'anystay-e2a14.appspot.com',
    measurementId: 'G-418VF4S68N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41K9fBeY1osJvLsBv1PPGITFw2uryaRw',
    appId: '1:88909482704:android:7898750dcf45628cbb2cd5',
    messagingSenderId: '88909482704',
    projectId: 'anystay-e2a14',
    storageBucket: 'anystay-e2a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi4FgTZ9WUz8AAXyb0l6SZVsHfKcrOpB0',
    appId: '1:88909482704:ios:11c0cc53d090eedbbb2cd5',
    messagingSenderId: '88909482704',
    projectId: 'anystay-e2a14',
    storageBucket: 'anystay-e2a14.appspot.com',
    iosBundleId: 'com.example.flutterApplicationHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi4FgTZ9WUz8AAXyb0l6SZVsHfKcrOpB0',
    appId: '1:88909482704:ios:11c0cc53d090eedbbb2cd5',
    messagingSenderId: '88909482704',
    projectId: 'anystay-e2a14',
    storageBucket: 'anystay-e2a14.appspot.com',
    iosBundleId: 'com.example.flutterApplicationHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzJtc33sAZgzpOjhn_TjX0hxBCd5_BFck',
    appId: '1:88909482704:web:c18187daa099bd8ebb2cd5',
    messagingSenderId: '88909482704',
    projectId: 'anystay-e2a14',
    authDomain: 'anystay-e2a14.firebaseapp.com',
    storageBucket: 'anystay-e2a14.appspot.com',
    measurementId: 'G-BMJQXWQ7EK',
  );
}
